# Generated by Django 5.2.8 on 2025-11-13 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('department', models.CharField(choices=[('CS', 'Computer Science'), ('ME', 'Mechanical Engineering'), ('EC', 'Electronics & Communication'), ('CV', 'Civil Engineering'), ('EE', 'Electrical Engineering'), ('IS', 'Information Science')], max_length=2)),
                ('specialization', models.CharField(choices=[('AI', 'Artificial Intelligence'), ('ML', 'Machine Learning'), ('WEB', 'Web Development'), ('DB', 'Database Management'), ('NW', 'Networking'), ('OTHER', 'Other')], max_length=5)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('bio', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trainer',
                'verbose_name_plural': 'Trainers',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
